# Generated by Django 5.0 on 2024-01-10 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pMesDelta', models.DecimalField(decimal_places=6, default=1.0, max_digits=10)),
            ],
        ),
    ]
