# Generated by Django 3.2.19 on 2024-02-27 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_pressurepoint_switchstate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='globalvalues',
            old_name='currentPressure',
            new_name='currentCPressure',
        ),
        migrations.RenameField(
            model_name='pressurepoint',
            old_name='pressure',
            new_name='Cpressure',
        ),
        migrations.AddField(
            model_name='globalvalues',
            name='currentSPressure',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='globalvalues',
            name='dutyCycle',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='pressurepoint',
            name='Spressure',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
